services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    env_file:
      - path: ./.env
        required: true
    # ports: # for dev
    #   - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      # Database
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
      - IS_INIT_DB=${IS_INIT_DB}
      - MIGRATIONS_PATH=${MIGRATIONS_PATH}
      # Other
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_USE_SSL=${SUPABASE_USE_SSL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_BUCKET=${SUPABASE_BUCKET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - N8N_API_INTERNAL=http://n8n:5678
    networks:
      - local_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
        - "80:80"
        - "443:443"  # for HTTPS
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./certbot/conf:/etc/letsencrypt:ro
        - ./certbot/www:/var/www/certbot:ro
    networks:
      - local_network
    depends_on:
      - app
      - n8n
    restart: always

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_main
    env_file:
      - path: ./.env.n8n
        required: true
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - local_network
    restart: unless-stopped

networks:
  local_network:
    driver: bridge