CREATE TABLE IF NOT EXISTS public.languages(
       language_id SERIAL PRIMARY KEY NOT NULL,
       name TEXT NOT NULL,
       created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
       updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.languages (language_id, name)
VALUES
    (1, 'English'),
    (2, 'Russian'),
    (3, 'Serbian'),
    (4, 'Chinese'),
    (5, 'Spanish'),
    (6, 'Hindi'),
    (7, 'French'),
    (8, 'Arabic'),
    (9, 'Portuguese'),
    (10, 'Bengali'),
    (11, 'German'),
    (12, 'Japanese'),
    (13, 'Korean'),
    (14, 'Turkish'),
    (15, 'Italian'),
    (16, 'Vietnamese'),
    (17, 'Thai'),
    (18, 'Polish'),
    (19, 'Ukrainian'),
    (20, 'Dutch'),
    (21, 'Greek'),
    (22, 'Czech'),
    (23, 'Hungarian'),
    (24, 'Romanian'),
    (25, 'Bulgarian'),
    (26, 'Croatian'),
    (27, 'Bosnian'),
    (28, 'Slovenian'),
    (29, 'Swedish'),
    (30, 'Norwegian'),
    (31, 'Danish'),
    (32, 'Finnish'),
    (33, 'Hebrew'),
    (34, 'Persian'),
    (35, 'Urdu'),
    (36, 'Indonesian'),
    (37, 'Malay'),
    (38, 'Tagalog'),
    (39, 'Swahili'),
    (40, 'Tamil'),
    (41, 'Telugu'),
    (42, 'Marathi'),
    (43, 'Punjabi'),
    (44, 'Gujarati'),
    (45, 'Kannada'),
    (46, 'Malayalam'),
    (47, 'Odia'),
    (48, 'Afrikaans'),
    (49, 'Amharic'),
    (50, 'Hausa')
ON CONFLICT DO NOTHING;
